openapi: "3.1.0"
info:
  title: "Google Sheets Data API"
  description: "API for managing and retrieving data from a Google Sheet"
  version: "v1.0.0"
servers:
  - url: "[YOUR GOOGLE SCRIPT WEB APP URL]"
paths:
  /exec?operation=getPeople:
    get:
      description: Get a list of all people's names
      operationId: getPeople
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
      deprecated: false
  /exec?operation=getPerson:
    get:
      description: Get a specific person's details
      operationId: getPerson
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the person to retrieve
              required:
                - name
      deprecated: false
  /exec?operation=createProfile:
    post:
      description: Create a new person profile
      operationId: createProfile
      parameters:
        - name: name
          in: query
          description: Name of the person for whom the profile is being created
          required: true
          schema:
            type: string
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Template for creating a new profile
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                template:
                  type: string
                  description: JSON template for the new person profile
      deprecated: false
  /exec?operation=updateProfile:
    post:
      description: Update a specific field in a person's profile
      operationId: updateProfile
      parameters:
        - name: name
          in: query
          description: Name of the person whose profile is to be updated
          required: true
          schema:
            type: string
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Details for updating the person's profile
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
                  description: New value for the profile update
                path:
                  type: string
                  description: Path to the field within the profile to be updated
                updateType:
                  type: string
                  description: Type of update (overwrite/append)
              required:
                - value
                - path
                - updateType
      deprecated: false
  /exec?operation=createEvent:
    post:
      description: Create a new event in Google Calendar
      operationId: createEvent
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Request body for creating a new event
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the event
                startDateTime:
                  type: string
                  description: Start date and time in 'MMMM D, YYYY HH:mm:ss' format, e.g., 'January 1, 2024 20:00:00'
                endDateTime:
                  type: string
                  description: End date and time in 'MMMM D, YYYY HH:mm:ss' format, e.g., 'January 1, 2024 21:00:00'
                isAllDay:
                  type: boolean
                  description: Set to true for all-day events, false for specific time events
                description:
                  type: string
                  description: Description or details of the event (optional)
                invitees:
                  type: array
                  items:
                    type: string
                  description: Array of email addresses of invitees (optional)
                color:
                  type: string
                  description: Color of the calendar event
                  enum: [PALE_BLUE, PALE_GREEN, MAUVE, PALE_RED, YELLOW, ORANGE, CYAN, GRAY, BLUE, GREEN, RED]
              required:
                - title
                - startDateTime
                - endDateTime
      deprecated: false
  /exec?operation=viewEvents:
    post:
      description: See all events in a specified timeframe for your Google Calendar
      operationId: viewEvents
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Request body for viewing events with start and end date filters
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                startDateTime:
                  type: string
                  description: Start datetime filter date and time in 'MMMM D, YYYY HH:mm:ss' format, e.g., 'January 1, 2024 20:00:00'
                endDateTime:
                  type: string
                  description: End datetime filter date and time in 'MMMM D, YYYY HH:mm:ss' format, e.g., 'January 1, 2024 21:00:00'
              required:
                - startDateTime
                - endDateTime
      deprecated: false
  /exec?operation=modifyEvent:
    post:
      description: Updates existing calendar events using an event ID
      operationId: modifyEvent
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Request body for updating and existing event
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eventId:
                  type: string
                  description: The ID of the event which can be found using the getEvents call
                title:
                  type: string
                  description: Title of the event (optional)
                startDateTime:
                  type: string
                  description: Updated the start date and time in 'MMMM D, YYYY HH:mm:ss' format, e.g., 'January 1, 2024 20:00:00' (if
                    modifying date/time, must include both new start and end times)
                endDateTime:
                  type: string
                  description: Updates the end date and time in 'MMMM D, YYYY HH:mm:ss' format, e.g., 'January 1, 2024 21:00:00' (if
                    modifying date/time, must include both new start and end times)
                isAllDay:
                  type: boolean
                  description: If true, updates event to be an all day event
                description:
                  type: string
                  description: Updates the description or details of the event (optional)
                deleteEvent:
                  type: boolean
                  description: If true, deletes the event (optional)
                color:
                  type: string
                  description: New color for the calendar event
                  enum: [PALE_BLUE, PALE_GREEN, MAUVE, PALE_RED, YELLOW, ORANGE, CYAN, GRAY, BLUE, GREEN, RED]
              required:
                - eventId
      deprecated: false
  /exec?operation=getEmails:
    post:
      description: Returns email information based on body filters
      operationId: getEmails
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Filters which emails are returned in the response
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                minDate:
                  type: string
                  description: "How far back to look for emails formatted like: 'YYYY-MM-DD'"
                isUnread:
                  type: boolean
                  description: If true, will only return unread emails
                isInInbox:
                  type: boolean
                  descrition: If true, will only return emails currently in the user's inbox
              required:
                - minDate
      deprecated: false
  /exec?operation=updateEmails:
    post:
      description: Performs uodate actions on selected emails
      operationId: updateEmails
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Filters which emails are returned in the response
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                emailIds:
                  type: array
                  items:
                    type: string
                    description: ID of emails to be updated
                markAsRead:
                  type: boolean
                  description: If true, will mark emails as read. If false, will mark emails as unread. If null, will not change read
                    status.
                archive:
                  type: boolean
                  descrition: If true, will archive emails
                moveToInbox:
                  type: boolean
                  descrition: If true, will move emails back to inbox
              required:
                - emailIds
      deprecated: false
  /exec?operation=draftReply:
    post:
      description: Creates a draft reply to an email
      operationId: draftReply
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Relevent information for the draft response
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                emailId:
                  type: string
                  description: The ID of the email to create a response draft for
                draftContent:
                  type: string
                  description: The content of the drafted reply
                replyAll:
                  type: boolean
                  descrition: If true, will reply all, else will reply to the sender only
              required:
                - emailId
      deprecated: false
  /exec?operation=getEmailContext:
    post:
      description: Retrieves the email content for the entire email thread
      operationId: getEmailContext
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Which email should be investigated
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                emailId:
                  type: string
                  description: The ID of the email get context for
              required:
                - emailId
      deprecated: false
  /exec?operation=getObsidianVaultStructure:
    get:
      description: Retrieves the complete folder structure of your Obsidian vault stored in Google Drive, including folder names and IDs.
      operationId: getObsidianVaultStructure
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      deprecated: false
  /exec?operation=searchObsidianNotes:
    get:
      description: Performs a fuzzy search across all markdown notes in your Obsidian vault and returns matching notes with their full paths.
      operationId: searchObsidianNotes
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                folderId:
                  type: string
                  description: The ID of the folder to search in
                searchTerm:
                  type: string
                  description: Search term to find files
              required:
                - folderId
                - searchTerm
      deprecated: false
  /exec?operation=previewObsidianFolder:
    get:
      description: Shows a preview of the first 10 notes/files in a specified Obsidian vault folder.
      operationId: previewObsidianFolder
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                folderId:
                  type: string
                  description: The ID of the folder to preview contents
              required:
                - folderId
      deprecated: false
  /exec?operation=createObsidianNote:
    post:
      description: Creates a new markdown note in your Obsidian vault, replacing any existing note with the same name.
      operationId: createObsidianNote
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Information for creating a new markdown file
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                folderId:
                  type: string
                  description: The ID of the folder where the file should be stored
                fileName:
                  type: string
                  description: The name of the markdown file (should end with .md)
                content:
                  type: string
                  description: The content to be written into the markdown file
              required:
                - folderId
                - fileName
                - content
      deprecated: false
  /exec?operation=readObsidianNote:
    post:
      description: Reads the contents of a specific markdown note from your Obsidian vault.
      operationId: readObsidianNote
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fileId:
                  type: string
                  description: The ID of the Markdown file to read
              required:
                - fileId
      deprecated: false
  /exec?operation=createObsidianFolder:
    post:
      description: Creates a new folder within your Obsidian vault structure in Google Drive.
      operationId: createObsidianFolder
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Information for creating a new folder
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parentFolderId:
                  type: string
                  description: The ID of the parent folder where the new folder should be created
                folderName:
                  type: string
                  description: The name of the new folder
              required:
                - parentFolderId
                - folderName
      deprecated: false
  /exec?operation=moveObsidianItem:
    post:
      description: Moves a file or folder to a new location within your Obsidian vault in Google Drive.
      operationId: moveObsidianItem
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        description: Information about the item being moved
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                itemId:
                  type: string
                  description: The ID of the file or folder to move
                destinationFolderId:
                  type: string
                  description: The ID of the destination folder
                isFolder:
                  type: boolean
                  description: Whether the item to move is a folder (true) or file (false)
              required:
                - itemId
                - destinationFolderId
                - isFolder
      deprecated: false
  /exec?operation=deleteObsidianNote:
    post:
      description: Deletes a specific markdown note from your Obsidian vault in Google Drive.
      operationId: deleteObsidianNote
      parameters:
        - name: securityKey
          in: query
          description: Security key for authentication
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fileId:
                  type: string
                  description: The ID of the markdown note to delete
              required:
                - fileId
      deprecated: false
components:
  schemas: {}