openapi: "3.1.0"
info:
  title: "Google Sheets Data API"
  description: "API for managing and retrieving data from a Google Sheet"
  version: "v1.0.0"
servers:
  - url: "[YOUR GOOGLE SCRIPT WEB APP URL]"
paths:
  "/exec?operation=getPeople":
    get:
      description: "Get a list of all people's names"
      operationId: "getPeople"
      parameters:
        - name: "securityKey"
          in: "query"
          description: "Security key for authentication"
          required: true
          schema:
            type: "string"
      deprecated: false
  "/exec?operation=getPerson":
    get:
      description: "Get a specific person's details"
      operationId: "getPerson"
      parameters:
        - name: "name"
          in: "query"
          description: "Name of the person to retrieve"
          required: true
          schema:
            type: "string"
        - name: "securityKey"
          in: "query"
          description: "Security key for authentication"
          required: true
          schema:
            type: "string"
      deprecated: false
  "/exec?operation=createProfile":
    post:
      description: "Create a new person profile"
      operationId: "createProfile"
      parameters:
        - name: "name"
          in: "query"
          description: "Name of the person for whom the profile is being created"
          required: true
          schema:
            type: "string"
        - name: "securityKey"
          in: "query"
          description: "Security key for authentication"
          required: true
          schema:
            type: "string"
      requestBody:
        description: "Template for creating a new profile"
        required: false
        content:
          application/json:
            schema:
              type: "object"
              properties:
                template:
                  type: "string"
                  description: "JSON template for the new person profile"
      deprecated: false
  "/exec?operation=updateProfile":
    post:
      description: "Update a specific field in a person's profile"
      operationId: "updateProfile"
      parameters:
        - name: "name"
          in: "query"
          description: "Name of the person whose profile is to be updated"
          required: true
          schema:
            type: "string"
        - name: "securityKey"
          in: "query"
          description: "Security key for authentication"
          required: true
          schema:
            type: "string"
      requestBody:
        description: "Details for updating the person's profile"
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                value:
                  type: "string"
                  description: "New value for the profile update"
                path:
                  type: "string"
                  description: "Path to the field within the profile to be updated"
                updateType:
                  type: "string"
                  description: "Type of update (overwrite/append)"
              required:
                - "value"
                - "path"
                - "updateType"
      deprecated: false
components:
  schemas: {}